name: Publish Chart

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      octopus-version:
        description: 'The SemVer version of Octopus to publish.  e.g. 2022.4.20121'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.1'
          
      - name: Package Chart
        run: helm package --version '${{ inputs.octopus-version }}' --app-version '${{ inputs.octopus-version }}' 'charts/octopus-deploy'
        
      - name: Push Chart to DockerHub
        run: helm push 'octopus-deploy-${{ inputs.octopus-version }}.tgz' oci://registry-1.docker.io/octopusdeploy/octopusdeploy-helm
        
     
