name: test-values-migrations
run-name: "Test Values Migrations"

on:
  workflow_dispatch:
  pull_request: 
  push:
    paths:
      - 'charts/kubernetes-agent/values-migrations-tests/**'
      - 'charts/kubernetes-agent/values-migrations/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Build
        run: go build -v ./charts/kubernetes-agent/value-migrations-tests/...

      - name: Test
        run: go test -v ./charts/kubernetes-agent/value-migrations-tests/...
