name: test-values-migrations
run-name: "Test Values Migrations"

on:
  workflow_dispatch:
  pull_request: 
  push:
    paths:
      - 'charts/kubernetes-agent/values-migrations-tests/**'
      - 'charts/kubernetes-agent/values-migrations/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          cache-dependency-path: "**/go.sum"

      - name: Test
        working-directory: charts/kubernetes-agent/value-migrations-tests
        run:  go test -v 
